---
title: "MA679-GAM hw"
author: "Ziyi Bai"
date: "2/26/2021"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
pacman::p_load("boot","splines","leaps","ISLR","mgcv","MASS")
```

## 7.3
```{r}
X <- seq(-2,2,0.1)
Y = 1+1*X-2*((X-1)^2*I(X>=1))
plot(X,Y,type = "l")
```

## 7.9
## (a)
```{r}
data("Boston")
fit_7.9a <- glm(nox~poly(dis,3),data=Boston)
summary(fit_7.9a)
plot(fit_7.9a)
```
```{r}
lims_dis <- range(Boston$dis)
grid_dis <- seq(lims_dis[1],lims_dis[2])
pred1 <- predict(fit_7.9a,list(dis=grid_dis), se=T)
se_lines <- cbind(pred1$fit+2*pred1$se.fit,pred1$fit-2*pred1$se.fit)
plot(Boston$dis,Boston$nox,xlab="Weighted Mean of Distance",ylab = "Nitrogen Oxide Concentration", col="dodgerblue4")
lines(grid_dis,pred1$fit,col="orange",lwd=2)
matlines(grid_dis,se_lines,lwd=2,col="red",lty=3)
```

##(b)
```{r}
set.seed(1)
rss <- rep(NA,10)
for (i in 1:10){
  fit_7.9b <- glm(nox~poly(dis,i),data=Boston)
  rss[i] <- sum(fit_7.9b$residuals^2)
}

plot(1:10,rss,xlab = "Polynomial Degree", ylab = "RSS", type="l",col="green",lwd=2)
points(which.min(rss),rss[which.min(rss)],col='red',pch=20,cex=2)
```
##(c)
```{r}
err <- rep(NA,10)
for (i in 1:10) {
  fit_7.9c <- glm(nox~poly(dis,i),data=Boston)
  err[i] <- cv.glm(Boston,fit_7.9c,K=10)$delta[1]
}

plot(1:10,err,xlab = "Polynomial Degree",ylab = "MSE",type="l",col="deeppink3",lwd=2)
points(which.min(err),err[which.min(err)],col='red',pch=20,cex=2)
```
##(d)
```{r}
range(Boston$dis)
summary(Boston$dis)

fit_7.9d <- lm(nox~bs(dis, df=4),data=Boston)
summary(fit_7.9d)

attr(bs(Boston$dis,df=4),"knots")

x<- seq(min(Boston$dis),max(Boston$dis))
y <- predict(fit_7.9d,data.frame(dis=x))
plot(Boston$dis,Boston$nox,col="blue")
lines(x,y,col="mediumorchid3",lwd=2)
```
R chosses the knot of 3.207

##(e)
```{r}
plot(Boston$dis,Boston$nox,xlab = "Weighted Mean of Distance", ylab="Nitrogen Oxide Concentration",col="gray40")
clrs <- rainbow(16)
legend(x="topright",legend = 3:16,text.col = clrs[3:16],text.width = 0.2,bty="n",horiz=T)
x <- seq(min(Boston$dis),max(Boston$dis),length.out=100)
rss_df <- c()
for (i in 3:16){
  fit_7.9e <- lm(nox~bs(dis,df=i),data=Boston)
  pred <- predict(fit_7.9e,data.frame(dis=x))
  lines(x,pred,col=clrs[i],lwd=1.85)
  rss_df[i] <- sum(fit_7.9e$residuals^2)
}

plot(1:16,rss_df,xlab = "Degree of Freedom", ylab="RSS",type="l",col="deeppink1",lwd=2)
points(which.min(rss_df),rss_df[which.min(rss_df)],col='orange',pch=20,cex=2)
```
##(f)
```{r}
set.seed(9)
cv <- rep(NA,16)
for (i in 3:16) {
  fit_7.9f <- glm(nox~bs(dis,df=i),data = Boston)
  cv[i] <- cv.glm(Boston,fit_7.9f,K=10)$delta[1]
}

plot(3:16, cv[3:16],xlab = "Degree of Freedom", ylab="Test MSE",type="l")
points(which.min(cv),cv[which.min(cv)],col="red",pch=20,cex=2)
```

## 7.10
```{r}
data("College")
set.seed(1)
train_id <- sample(1:nrow(College),500)
train <- College[train_id,]
test <- College[-train_id]

fit_fwd <- regsubsets(Outstate~., train, nvmax = ncol(College)-1,method="forward")
fwd_summary <- summary(fit_fwd)

test_mat <- model.matrix(Outstate~., test, nvmax=ncol(College)-1)
```
```{}
err_fwd <- rep(NA,ncol(College)-1)
for (i in 1:(ncol(College)-1)) {
  coeff <- coef(fit_fwd,id=i)
  pred_fwd <- test_mat[,names(coeff)] %*% coeff
  err_fwd[i] <- mean((test$Outstate-pred_fwd)^2)
}
par(mfrow = c(2,2))
plot(err_fwd, type = "b", main = "Test MSE", xlab = "Number of Predictors")
min_mse <- which.min(err_fwd)
points(min_mse, err_fwd[min_mse], col = "red", pch = 4, lwd = 5)
plot(fwd_summary$adjr2, type = "b", main = "Adjusted R^2", xlab = "Number of Predictors")
max_adjr <- which.max(fwd_summary$adjr2)
points(max_adjr, fwd_summary$adjr2[max_adjr], col = "red", pch = 4, lwd = 5)
plot(fwd_summary$cp, type = "b", main = "Cp", xlab = "Number of Predictors")
min_cp <- which.min(fwd_summary$cp)
points(min_cp, fwd_summary$cp[min_cp], col = "red", pch = 4, lwd = 5)
plot(fwd_summary$bic, type = "b", main = "BIC", xlab = "Number of Predictors")
min_bic <- which.min(fwd_summary$bic)
points(min_bic, fwd_summary$bic[min_bic], col = "red", pch = 4, lwd = 5)
```

##(b)
```{r}
#install.packages("gam")
library(gam)
gam1 <- gam(Outstate ~ Private + s(Accept) + s(F.Undergrad) + s(Room.Board) + s(Personal) + s(Terminal) + s(S.F.Ratio) + s(perc.alumni) + s(Expend) + s(Grad.Rate), data = train)
par(mfrow = c(1,3))
plot(gam1, se = TRUE, col = "blue")
```
##(c)

pred_gam <- predict(gam1,test)
err_gam <- mean((test$Outstate-pred_gam)^2)
err_gam

tss_gam <- mean(((test$Outstate)-mean(test$Outstate))^2)
rss_gam <- 1-err_gam/tss_gam
rss_gam


##(d)
```{r}
summary(gam1)
```

## 7.11
##(a)
```{r}
set.seed(99)
X1 <- rnorm(100)
X2 <- rnorm(100)
eps <- rnorm(1:100,sd=1)

b_0=0.8
b_1=-1.5
b_2=1
Y=b_0+b_1*X1+b_2*X2+eps
plot(Y)
```
##(b)
```{r}
b_h1 <-3
```

##(c)
```{r}
a=Y-b_h1*X1
b_h2=lm(a~X2)$coef[2]
```

##(d)
```{r}
a=Y-b_h2*X2
b_h1=lm(a~X1)$coef[2]
```

##(e)
```{r}
b_hat0 <- rep(0,1000)
b_hat1 <- rep(0,1000)
b_hat2 <- rep(0,1000)

for (i in 1:1000){
  a <- Y-b_hat1[i]*X1
  b_hat2[i] <- lm(a~X2)$coef[2]
  a <- Y-b_hat2[i]*X2
  b_hat1[i] <- lm(a~X1)$coef[2]
  b_hat0[i] <- lm(a~X1)$coef[1]
}

plot(b_hat0, ylab = "Estimates", type = "l",col="red",ylim = c(-2,2),xlim = c(0,100))
lines(b_hat1,col="blue")
lines(b_hat2,col="green")
```

##(f)
```{r}
fit_7.11f <- lm(Y~X1+X2)

plot(b_hat0, ylab = "Estimates", type = "l", col = "red", ylim = c(-2,2), xlim = c(0,100), lwd = 3)
lines(b_hat1, col = "blue", lwd = 3)
lines(b_hat2, col = "green", lwd = 3)
abline(h = coef(fit_7.11f)[1], lty = "dashed", col = "brown", lwd = 3)
abline(h = coef(fit_7.11f)[2], lty = "dashed", col = "black", lwd = 3)
abline(h = coef(fit_7.11f)[3], lty = "dashed", col = "orange", lwd = 3)
```

##(g)
```{r}
b <- data.frame(b_hat0, b_hat1, b_hat2)
head(b)
```
One is enough.









